apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: notify-hub-api
spec:
  results:
    - name: hub-notification
      description: copy of the notification send to slack
      value: $(tasks.set-hub-api-message.results.hub-api)
  tasks:
    - name: set-hub-api-message
      taskRef:
        name: check-api-status
    - name: slack-message
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: bot-name
          value: iHubBot
        - name: icon-emoji
          value: ':technologist:'
        - name: message
          value: $(tasks.set-hub-api-message.results.hub-api)
        - name: webhook-secret
          value: coreos-tektondev-webhook
